sudo: required
language: python
services: docker
python: 
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
env:
    global:
        - USE_NETWORK=true
before_install:
    - docker pull treasureboat/ssh
    - docker run --net=host -p 2222:22 -d treasureboat/ssh
    - docker inspect treasureboat/ssh 
    - docker ps
    - env
install: 
    - pip install -r requirements.txt
    - python setup.py install
script: nosetests -v

