sudo: required
language: python
services: docker
python: 
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
env:
    global:
        - USE_NETWORK=true
        - IP_ADDR=ifconfig eth0 | grep "inet addr" | cut -d":" -f2 | awk '{print $1}'
before_install:
    - docker pull treasureboat/ssh
    - docker run -p 2222:22 -d treasureboat/ssh 
    - docker inspect treasureboat/ssh 
    - env
install: 
    - pip install -r requirements.txt
    - python setup.py install
script: nosetests -v

